package io.github.hyjn.nexori.plugin.travel;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

final class PendingArrivalTest {

    @Test
    void preservesAllFields() {
        PendingArrival arrival = new PendingArrival(
            "op-1", "srv-origin", "origin.srv:25565",
            "target-lobby", "Lobby", "NATURAL_SPAWN",
            "overworld", "natural_spawn", "keep_inventory",
            "Welcome!", "{}", "{\"meta\":true}"
        );
        assertEquals("op-1", arrival.travelOperationId());
        assertEquals("srv-origin", arrival.sourceServerId());
        assertEquals("origin.srv:25565", arrival.sourceConnectionAddress());
        assertEquals("target-lobby", arrival.destinationTargetId());
        assertEquals("Lobby", arrival.destinationTargetDisplayName());
        assertEquals("NATURAL_SPAWN", arrival.destinationTargetKind());
        assertEquals("overworld", arrival.worldName());
        assertEquals("natural_spawn", arrival.arrivalPointId());
        assertEquals("keep_inventory", arrival.travelProfileId());
        assertEquals("Welcome!", arrival.arrivalMessage());
        assertEquals("{}", arrival.contextJson());
        assertEquals("{\"meta\":true}", arrival.metadataJson());
    }

    @Test
    void allowsNullFieldsAccordingToCurrentBehavior() {
        PendingArrival arrival = new PendingArrival(
            null, null, null, null, null, null,
            null, null, null, null, null, null
        );
        assertNull(arrival.travelOperationId(),
            "Record constructor does not validate fields; null is preserved as-is");
        assertNull(arrival.contextJson());
        assertNull(arrival.metadataJson());
    }

    @Test
    void contextAndMetadataPreservedExactly() {
        String contextJson = "{\"launchMode\":\"minigame\",\"queueId\":\"queue-1\"}";
        String metadataJson = "{\"autoGenerated\":true,\"version\":2}";
        PendingArrival arrival = new PendingArrival(
            "op-1", "srv-1", "srv.host:25565",
            "target-1", "Target", "PORTAL",
            "world", "arrival-pt", "apply_inventory",
            "", contextJson, metadataJson
        );
        assertEquals(contextJson, arrival.contextJson());
        assertEquals(metadataJson, arrival.metadataJson());
    }

    @Test
    void travelProfileIdPreservedExactly() {
        PendingArrival arrival = new PendingArrival(
            "op-1", "srv-1", "srv.host:25565",
            "t", "T", "NATURAL_SPAWN",
            "world", "", "apply_inventory",
            "", "{}", "{}"
        );
        assertEquals("apply_inventory", arrival.travelProfileId());
    }
}
